version: '3.8'

services:
  app:
    build:
      context: ./backend # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # Map host port 5001 to container port 5001
    restart: unless-stopped
    networks:
      - shared-net

networks:
  shared-net:
    external: true